# Generated by Django 6.0.2 on 2026-05-18 08:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер категорії')),
                ('category_name', models.CharField(max_length=50, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_employee', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('empl_surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('empl_name', models.CharField(max_length=50, verbose_name='Ім*я')),
                ('empl_patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Побатькові')),
                ('empl_role', models.CharField(choices=[('Менеджер', 'Менеджер'), ('Касир', 'Касир')], max_length=10, verbose_name='Роль')),
                ('salary', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='Заробітна плата')),
                ('date_of_birth', models.DateField(validators=[main.models.validate_employee_age], verbose_name='Дата народження')),
                ('date_of_start', models.DateField(verbose_name='Дата початку роботи')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +38012345678', regex='^\\+380')], verbose_name='Номер телефону')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('street', models.CharField(max_length=50, verbose_name='Вулиця')),
                ('zip_code', models.CharField(max_length=9, verbose_name='Поштовий індекс')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('card_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('cust_surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('cust_name', models.CharField(max_length=50, verbose_name='Ім*я')),
                ('cust_patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Побатькові')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +38012345678', regex='^\\+380')], verbose_name='Номер телефону')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Місто')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вулиця')),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='Поштовий індекс')),
                ('percent', models.IntegerField(verbose_name='Відсоток знижки')),
            ],
            options={
                'verbose_name': 'Карта клієнта',
                'verbose_name_plural': 'Карти клієнтів',
                'db_table': 'CustomerCard',
                'constraints': [models.CheckConstraint(condition=models.Q(('percent__gte', 0)), name='percent_non_negative'), models.CheckConstraint(condition=models.Q(('phone_number__startswith', '+380')), name='phone_number_startswith_380')],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('check_number', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('print_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
                ('sum_total', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='Сума')),
                ('vat', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='ПДВ')),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Код працівника')),
                ('card_number', models.ForeignKey(blank=True, db_column='card_number', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.customercard', verbose_name='Номер карти лояльності')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'db_table': 'StoreCheck',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False, verbose_name='ID продукту')),
                ('product_name', models.CharField(max_length=50, verbose_name='Назва')),
                ('characteristics', models.CharField(max_length=100, verbose_name='Опис')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Виробник')),
                ('category_number', models.ForeignKey(db_column='category_number', on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Номер категорії')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('upc', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('selling_price', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='Ціна')),
                ('products_number', models.IntegerField(verbose_name='Кількість одиниць')),
                ('promotional_product', models.BooleanField(default=False, verbose_name='Акційний продукт')),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.PROTECT, to='main.product')),
                ('upc_prom', models.ForeignKey(blank=True, db_column='upc_prom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_copies', to='main.storeproduct')),
            ],
            options={
                'verbose_name': 'Наявний продукт',
                'verbose_name_plural': 'Наявні продукти',
                'db_table': 'StoreProduct',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.IntegerField(verbose_name='Кількість одиниць')),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='Ціна')),
                ('check_number', models.ForeignKey(db_column='check_number', on_delete=django.db.models.deletion.CASCADE, to='main.check')),
                ('upc', models.ForeignKey(db_column='upc', on_delete=django.db.models.deletion.PROTECT, to='main.storeproduct')),
            ],
            options={
                'verbose_name': 'Продано',
                'verbose_name_plural': 'Продано',
                'db_table': 'Sale',
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('salary__gte', 0)), name='salary_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('phone_number__startswith', '+380')), name='empl_phone_number_startswith_380'),
        ),
        migrations.AddConstraint(
            model_name='check',
            constraint=models.CheckConstraint(condition=models.Q(('sum_total__gte', 0)), name='sum_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='check',
            constraint=models.CheckConstraint(condition=models.Q(('vat__gte', 0)), name='vat_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='selling_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(condition=models.Q(('products_number__gte', 0)), name='products_number_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('upc', 'check_number'), name='unique_sale_item'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('product_number__gte', 0)), name='sale_product_number_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='sale_selling_price_non_negative'),
        ),
    ]
