# Generated by Django 6.0.2 on 2026-05-16 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер категорії'),
        ),
        migrations.AlterField(
            model_name='check',
            name='check_number',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='check',
            name='print_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='check',
            name='sum_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='check',
            name='vat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='ПДВ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID продукту'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='Ціна'),
        ),
    ]
